### ISSUE TITLE
infos

### ISSUE THREAD

**Issue by ghost** [neatpro/Quasar-JWT#1]
good morning, sorry for my english. Can you help me? where i can set the endpoints for autentication?

**Comment by neatpro** [comment]
https://github.com/neatpro/Quasar-JWT/blob/master/src/router/index.js#L31

**Comment by ghost** [comment]
sorry, I explained myself badly in my question. i need to autenticate the user from a laravel passport server, I see that your suggest it's the base pointer for all the apis (and this is good for all the crud request). my problem is auth.  For example, with oauth2 i take the token with "/oauth/token", where i can set it?

**Comment by neatpro** [comment]
This starter kit is for the authentication using JWT not for Laravel Passport and/or Oauth2.

**Comment by ghost** [comment]
thank youso much @neatpro. I have follow your suggests and now when i put email and password quasar connect correctly to my apis and api return me access_token and refresh token. I have set /account for redirect, but the sistem load login another time, as if don' store the token.

can you help me?

**Comment by neatpro** [comment]
https://github.com/websanova/vue-auth

**Comment by ghost** [comment]
i'm sorry @neatpro, I apologize for you, I do not want to obsess you. when i send the request to api, i receive the response with the access_token and refresh_token. the problem is when the script request /auth/user. the api respond with 401. in the header the script don't put the token in automatic.

i don't undestand how i must to configure the axios for insert the token into header manually.
